#!/usr/bin/env bash
# PreToolUse guard (matcher: Write|Edit) for Unity projects — part of claude-unity-devkit.
#
# Blocks:
#   1. Any write under a Unity project's Library/, Temp/, or Logs/. Unity owns those folders;
#      edits there are overwritten on the next import or corrupt the asset database.
#   2. Any write to a *.meta file unless its asset is also in the current change set (git status
#      shows the asset as added, modified, deleted, or untracked). A .meta carries the GUID that
#      scenes and prefabs reference, so it should only ever change together with its asset.
#
# "Unity project" = the nearest ancestor of the edited file holding both Assets/ and
# ProjectSettings/. Outside a Unity project this hook does nothing, so it is safe everywhere.
# Reads the hook JSON on stdin; uses jq, else python3, else a sed fallback.
set -uo pipefail
set -f # no globbing: paths are handled as plain strings

input="$(cat)"

extract() { # extract <jq-path> <python-expr-over-d>
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$input" | jq -r "$1 // empty" 2>/dev/null
  elif command -v python3 >/dev/null 2>&1; then
    printf '%s' "$input" | python3 -c "import sys,json; d=json.load(sys.stdin); print($2 or '')" 2>/dev/null
  fi
}

json_string() {
  printf '"%s"' "$(printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g')"
}

deny() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":%s}}\n' "$(json_string "$1")"
  echo "$1" >&2
  exit 2
}

ask() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"ask","permissionDecisionReason":%s}}\n' "$(json_string "$1")"
  exit 0
}

normalize() { # collapse ./ and ../ without requiring the path to exist
  local IFS=/ part
  local -a out=()
  for part in $1; do
    case "$part" in
      '' | .) ;;
      ..) [[ ${#out[@]} -gt 0 ]] && unset 'out[${#out[@]}-1]' ;;
      *) out+=("$part") ;;
    esac
  done
  printf '/%s' "${out[@]}"
}

file_path="$(extract '.tool_input.file_path' 'd.get("tool_input", {}).get("file_path")')"
cwd="$(extract '.cwd' 'd.get("cwd")')"
if [[ -z "$file_path" ]]; then
  file_path="$(printf '%s' "$input" | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1)"
fi
[[ -n "$file_path" ]] || exit 0

cwd="${cwd:-$PWD}"
[[ "$file_path" == /* ]] || file_path="$cwd/$file_path"
file_path="$(normalize "$file_path")"

# Find the Unity project root that contains this file.
root=""
dir="$(dirname "$file_path")"
while [[ -n "$dir" && "$dir" != "/" ]]; do
  if [[ -d "$dir/Assets" && -d "$dir/ProjectSettings" ]]; then
    root="$dir"
    break
  fi
  dir="$(dirname "$dir")"
done
[[ -n "$root" ]] || exit 0

rel="${file_path#"$root"/}"
top="$(printf '%s' "${rel%%/*}" | tr '[:upper:]' '[:lower:]')"

if [[ "$rel" == */* ]]; then
  case "$top" in
    library | temp | logs)
      deny "Blocked write to ${rel}: ${rel%%/*}/ is generated by the Unity Editor (import cache, temp files, logs) and must never be edited by hand. Change the source asset under Assets/ or Packages/ instead."
      ;;
  esac
fi

if [[ "$file_path" == *.meta ]]; then
  asset="${file_path%.meta}"
  if ! git -C "$root" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    ask "Editing ${rel}: .meta files are Unity-generated and hold the asset GUID. This is not a git repo, so the hook cannot confirm ${rel%.meta} is changing too. Approve only if the asset is part of this change."
  fi
  changes="$(git -C "$root" status --porcelain --untracked-files=all -- "$asset" 2>/dev/null)"
  [[ -n "$changes" ]] && exit 0
  deny "Blocked edit to ${rel}: .meta files are Unity-generated (they carry the GUID that scenes and prefabs reference). Only edit a .meta in the same change as its asset (${rel%.meta}): change the asset first, or let the Unity Editor regenerate the .meta."
fi

exit 0
